### ISSUE TITLE
I can't run tests in series

### ISSUE THREAD

**Issue by AndyRubio** [TestFX/TestFX#492]
I've got 2 testfx tests which each run successfully but when run in series, fail. The error message is:

    --- Exception in Async Thread ---
     java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Cannot set style once stage has been set visible
    java.util.concurrent.FutureTask.report(FutureTask.java:122)
    ...

I initialised the test by creating the stage:

    @Before
    public void setUp() throws Exception {

    FxToolkit.registerPrimaryStage();
    setupStage((stage -> {

        Undecorator undecorator;
        ....

I'm guessing that the thread isn't letting go of the stage after the first time round. I've tried several things to kill it before the second test starts including `FxToolkit.hideStage();` and `Platform.exit();`.

I'm using `org.testfx:testfx-junit:4.0.6-alpha`. Any thoughts?

Thanks, Andy

**Comment by brcolow** [comment]
Would it be possible to see the entire test source code?

**Comment by AndyRubio** [comment]
Thanks, as I prpared to answer your question you acted as my 'rubber duck', and my problem is now solved! 👍 

FYI I had this line:

`stage.initStyle(StageStyle.TRANSPARENT);`

within the `setupStage` block. I've commented it out and everything runs. The block was:

    setupStage((stage -> {
            Undecorator undecorator;
            final ApplicationContext applicationContext = new AnnotationConfigApplicationContext(SpringConfiguration.class);
            final AppProperties config = applicationContext.getBean(AppProperties.class);
            final TextArea console = new TextArea();
            final ProjectsLoader projectsLoader = new ProjectsLoader(console);
            final TextField strataPathTextField = new TextField();
            ListView<String> projectsView = new ListView<>();
            final GUI gui = new GUI(projectsView, console);    
            undecorator = new Undecorator(stage, root);
            undecorator.getStylesheets().add("/windowStyle.css");
            undecorator.getBackgroundRect().setStyle("-fx-fill: rgba(" + config.getWindowColor() + ");");
            undecorator.setFadeInTransition();

            final Scene scene = new Scene(undecorator, 1400, 680, Color.TRANSPARENT);
            stage.initStyle(StageStyle.TRANSPARENT);
            new Tray().createTrayIcon(undecorator.getStage());
            stage.setScene(scene);
            stage.show();
            projectsLoader.loadProjectsToView(strataPathTextField.getText());

            nodes = paneNodes(root);
        }));

        FxToolkit.showStage();

I don't enough of the inner workings to understand why `stage.initStyle(StageStyle.TRANSPARENT);` appears to cause the problem initially described though.

**Comment by brcolow** [comment]
Thanks, glad you found a work-around. I will have to think about this and see if there is anything to be done on the TestFX side of things. You are expecting TestFX to pass you a newly created Stage in the lambda parameter of `setupStage`, correct? Need to think if it always makes sense to return a new Stage, or at least make that the default.

**Comment by stefanofornari** [comment]
I am running into the same problem (I lot of time has passed ...). I guess removing the stage.initStyle(StageStyle.TRANSPARENT); does not solve the problem because it could be any code that set the styles... each run should have its own Stage.

**Comment by tcfurrer** [comment]
I just hit this too.  Of course another workaround (for us gradle folks) is to use forkEvery=1. That results in significantly increased test suite runtimes, but since TestFX suites already tend to be too slow to run interactively, in at least some projects this may be acceptable.  Unfortunately in mine right now, it isn't.

Looks like the issue stems from the fact that PrimaryStageApplication runs once at completes PRIMARY_STAGE_FUTURE (which is a static variable), and FxToolkit.registerPrimaryStage() always returns the stage created there because of the qualification on primaryStageFuture.isDone() in ToolkitServiceImpl.setupPrimaryStage() (note that the primaryStageFuture passed in there is the same instance as PrimaryStageApplication.PRIMARY_STAGE_FUTURE).

I initially wanted to apply a workaround to qualify my own stage.initStyle() call with a check that the style was not already set as desired.  But since PrimaryStageApplication.start() itself always calls stage.initStyle(UNDECORATED), that doesn't work in any cases where my own stage.initStyle() needs to set any style other than UNDECORATED.

Another workaround idea was to avoid the use of FxToolkit.registerPrimaryStage() by changing all TestFX tests to instead use ApplicationExtension.  That doesn't work because ApplicationExtension ends up using FxToolkit.registerPrimaryStage() under it's hood anyway.

So that brings me back to the aforementioned workaround, which is to avoid calling Stage.initStyle() during all TestFX tests.  This has two limitations: 1) it is impossible to test a Stage which is anything other than UNDECORATED, and 2) it requires qualifying the production code's call to initStyle() to suppress it when running tests, which is an undesirable (but often acceptable) production vs test behavior divergence.

**Comment by mvsoder** [comment]
I just got this fixed for the next release of TestFX.

**Comment by mvsoder** [comment]
@tcfurrer You might consider trying FxToolkit.registerStage(Supplier<Stage>) and not using the primary stage. That way you can control the way the stage style is initialized.
